### ISSUE TITLE
Error running LSP server

### ISSUE THREAD

**Issue by overtube** [slint-ui/slint-cpp-template#15]
```Error running LSP server: unexpected message during shutdown: Response(Response { id: RequestId(I32(0)), result: None, error: Some(ResponseError { code: -32601, message: "Unhandled method workspace/configuration", data: None }) })```

**Comment by ogoffart** [comment]
What's your version of Slint? What editor do you use? When does this error happen? How do you reproduce it?

**Comment by overtube** [comment]
```Slint (Nightly) v2023.6.2103 Preview
Version: 1.79.2
Release: 23166
Commit: 19c0f5cefaeb2637b45a9c7a356151fcfdcda1e9
Date: 2023-06-15T18:19:23.116Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x86_64

So, I just push build button, 
after all be done and prepeared, without errors, and this is happen
```

**Comment by overtube** [comment]
thx for fix it! I use nightly, all is worked now
