### ISSUE TITLE
find_package(Slint) never succeed even after FetchContent_MakeAvailable

### ISSUE THREAD

**Issue by Centaur** [slint-ui/slint-cpp-template#16]
This causes Slint source code being retrieved every time a cmake configuration is triggered.

> CMake Warning at CMakeLists.txt:4 (find_package):
> [cmake]   By not providing "FindSlint.cmake" in CMAKE_MODULE_PATH this project has
> [cmake]   asked CMake to find a package configuration file provided by "Slint", but
> [cmake]   CMake did not find one.
> [cmake] 
> [cmake]   Could not find a package configuration file provided by "Slint" with any of
> [cmake]   the following names:
> [cmake] 
> [cmake]     SlintConfig.cmake
> [cmake]     slint-config.cmake
> [cmake] 
> [cmake]   Add the installation prefix of "Slint" to CMAKE_PREFIX_PATH or set
> [cmake]   "Slint_DIR" to a directory containing one of the above files.  If "Slint"
> [cmake]   provides a separate development package or SDK, be sure it has been
> [cmake]   installed.

**Comment by ogoffart** [comment]
Please copy your full CMakeLists then.
find_package only work if you have installed the slint library somehow and passed the paths to cmake.
if the package is not found, we call FetchContent_Declare/FetchContent_MakeAvailable instead. If that fails, do cmake show errors?

**Comment by Centaur** [comment]
@ogoffart I know that is current behavior, but not neccessary a reasonable one.
I expect cmake should be smart enough to find slint after FetchContent_Declare/FetchContent_MakeAvailable/Slint build, instead of doing slint fetch/build everytime a cmake configuration is triggered.

**Comment by ogoffart** [comment]
I'm afraid this is not how cmake work.
This would probably be a feature request for cmake.
Or if you find a way to make it work, please open a pull request.

**Comment by Centaur** [comment]
My bad.
After `set(FETCHCONTENT_QUIET OFF)` I see what `FetchContent` actually does. It will not repeat the `clone` but just do `update`, and if nothing changes, Slint source code will not be build again. That is reasonable.
Please accept my apology. 
Thank you for your patience.

**Comment by tronical** [comment]
No worries - all good. I'll also close the PR. The current approach isn't too bad and it works with older cmake versions.
