### ISSUE TITLE
For windows, automatically copy DLLs from system installation to output binary directory.

### ISSUE THREAD

**Issue by lasagnaphil** [slint-ui/slint-cpp-template#5]
Currently (on Windows), when I compile and run the repo with CMake I get an error that "slint_cpp.dll" (and all the accompanying Qt6 libraries) are not found. I can copy these manually from the system directory to my output directory, but this is a bit cumbersome. Ideally there should be a CMake function that automatically does this. (I'm not sure if this should be done on this template repo or the main slint repo though.)

**Comment by lasagnaphil** [comment]
Related: probably this? https://github.com/slint-ui/slint/issues/1025

**Comment by tronical** [comment]
Yes, that's right. And there's now a patch in upstream corrosion that helps with this - needs some fixing/testing though.

**Comment by tronical** [comment]
This is fixed now with https://github.com/slint-ui/slint-cpp-template/pull/7
