### ISSUE TITLE
Is there a way to build slint in release mode?

### ISSUE THREAD

**Issue by datawater** [slint-ui/slint-cpp-template#8]
I've noticed that cargo builds slint in debug mode, is there a way to build it in release mode?

**Comment by ogoffart** [comment]
With cmake, to build in release, you need to pass

```
-DCMAKE_BUILD_TYPE=Release
```

to your cmake command.

We probably should document that somewhere for those not too familiar with cmake.

**Comment by datawater** [comment]
Thank you!
